### ISSUE TITLE
OTA.ino example - onMessage function

### ISSUE THREAD

**Issue by dzid26** [jeroenvermeulen/JeVe_EasyOTA#9]
In OTA example char should be replaced with string:

OTA.onMessage([](**const String&** message, int line) {
    Serial.println(message);
    });

**Comment by jeroenvermeulen** [comment]
I have made this change: a8ea2a1be24cc89bf2653f6f17fc6cfe7dc439f9
But afterwards I started thinking there is probably automatic conversion between the types somewhere.
I did not update
`examples/OTA_LCD_I2C/OTA_LCD_I2C.ino` and `examples/OTA_Oled_U8g2/OTA_Oled_U8g2.ino` 
because they are a bit more complicated, and I would need my test setup before chaging anything.
Quite sure everyting did work with the current code.
Feel free to contribute updated examples, but make sure you test them with the right hardware for the examples.
